### PR TITLE
docker: add Dockerfile

### LINKED ISSUE #52: Docker image
Hi all,

I was trying to run the project locally and I managed to do it, but I thought it would be nice to provide a docker image (possibly reading `application.properties` from a specific file instead of classpath).

Are there any plans to do this? I can contribute if necessary

### PR DESCRIPTION
**Pull request by racevedoo**
This adds a Dockerfile based on java 11. It supports reading the config
file (application.properties) from a specific folder (`/opt/conf`),
making it easy to use in environments like Kubernetes, where it would be
a secret.

Closes #52

### CODE REVIEW

**Comment by racevedoo** [comment]
@ismailsimsek it would be great to add this to a public docker registry (maybe quay.io). Could you help me set this up?

**Comment by ismailsimsek** [comment]
definitely, i can connect to Docker hub(i have account there) and then we can add to quay.io later on. what do you think about github container registry? i believe it will be part of the current repo and we can use github action to publish images.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
found quick blog about it https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by racevedoo** [comment]
> definitely, i can connect to Docker hub(i have account there) and then we can add to quay.io later on. what do you think about github container registry? i believe it will be part of the current repo and we can use github action to publish images.
> 
> https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry found quick blog about it https://github.blog/2020-09-01-introducing-github-container-registry/

looks good too! any public registry works for me

**Comment by ismailsimsek** [comment]
@racevedoo merging it to release on docker hub. then maybe we can add action to release on github-container-registry

**Pull request merged**
